name: mobile_core
description: Core shared package for Livraison.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.0.0
  shared_preferences: ^2.0.0
  google_fonts: ^6.2.1
  package_info_plus: ^8.1.0
  firebase_analytics: ^12.0.0
  intl: ^0.18.1

flutter:
  uses-material-design: true
